name: Release and Deployment
on:
  push:
    branches: [prod]
  workflow_dispatch:

jobs:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.new_release_version }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
             npm install -D conventional-changelog-angular
      
      - name: Semantic Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx semantic-release --branches prod
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_release_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "Version released: ${NEW_VERSION}-prod"
